

Kubernetes get all pods in all namespaces and watch them
○ → kgp -A -w


Find Kubernetes API Version supported:
for kind in `kubectl api-resources | tail +2 | awk '{ print $1 }'`; do kubectl explain $kind; done | grep -e "KIND:" -e "VERSION:"


Kubernetes port forwarding:
Forward a port from a Pod to localhost to access content

○ → k port-forward  -n traefik-kafka traefik-kafka-controller-5549bc588f-2zwf6 32215:9000
○ → k port-forward  -n NAMESPACE       POD_NAME                                32215:CONTAINERPORT
