                        Minikube

1. Start your cluster
From a terminal with administrator access (but not logged in as root), run:

$ minikube start

2. Interact with your cluster
If you already have kubectl installed, you can now use it to access your shiny new cluster:

$ kubectl get po -A
Alternatively, minikube can download the appropriate version of kubectl and you should be able to use it like this:

$ minikube kubectl -- get po -A
You can also make your life easier by adding the following to your shell config:

$ alias kubectl="minikube kubectl --"
Initially, some services such as the storage-provisioner, may not yet be in a Running state. This is a normal condition during cluster bring-up, and will resolve itself momentarily. For additional insight into your cluster state, minikube bundles the Kubernetes Dashboard, allowing you to get easily acclimated to your new environment:

$ minikube dashboard


3a. Deploy applications
Create a sample deployment and expose it on port 8080:

kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment hello-minikube --type=NodePort --port=8080
It may take a moment, but your deployment will soon show up when you run:

kubectl get services hello-minikube
The easiest way to access this service is to let minikube launch a web browser for you:

minikube service hello-minikube
Alternatively, use kubectl to forward the port:

kubectl port-forward service/hello-minikube 7080:8080
Tada! Your application is now available at http://localhost:7080/.


3b. LoadBalancer deployments 
To access a LoadBalancer deployment, use the “minikube tunnel” command. Here is an example deployment:

kubectl create deployment balanced --image=k8s.gcr.io/echoserver:1.4  
kubectl expose deployment balanced --type=LoadBalancer --port=8080
In another window, start the tunnel to create a routable IP for the ‘balanced’ deployment:

minikube tunnel
To find the routable IP, run this command and examine the EXTERNAL-IP column:

kubectl get services balanced
Your deployment is now available at <EXTERNAL-IP>:8080


4. Manage your cluster
Pause Kubernetes without impacting deployed applications:

minikube pause
Unpause a paused instance:

minikube unpause
Halt the cluster:

minikube stop
Increase the default memory limit (requires a restart):

minikube config set memory 16384
Browse the catalog of easily installed Kubernetes services:

minikube addons list
Create a second cluster running an older Kubernetes release:

minikube start -p aged --kubernetes-version=v1.16.1
Delete all of the minikube clusters:

minikube delete --all




Known Issues:

  Issue 1:
  💥  initialization failed, will try again: run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.18.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,SystemVerification": Process exited with status 1

  Solution 1:
    Remove ~/.minikube directory and retry "minikube start"



