# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
  vb.memory = 256
  vb.cpus = 1
end
# Application server 1.
config.vm.define "app1" do |app1|
  app1.vm.hostname = "app1.dev"
  app1.vm.box = "centos/7"
  app1.vm.network :private_network, ip: "192.168.3.5"
end
# Application server 2.
config.vm.define "app2" do |app2|
  app2.vm.hostname = "app2.dev"
  app2.vm.box = "centos/7"
  app2.vm.network :private_network, ip: "192.168.3.6"
end
# Application server 3.
config.vm.define "app3" do |app3|
  app3.vm.hostname = "app3.dev"
  app3.vm.box = "centos/7"
  app3.vm.network :private_network, ip: "192.168.3.7"
end
end
